title: Trung Tran
email: tntrung@apcs.vn
description: > # this means to ignore newlines until "twitter_username:"
      Discover the world<br/>
      Get to know yourself<br/>
      Enjoy the process<br/>
      Youth is too precious to be sold for money.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  trungtipu
linkedin_username: trungtipu
facebook_username: trungtipu


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - blog.md
  - resume.md
